#!/bin/bash

set -eo pipefail

export PLATFORMS="linux/arm,linux/arm64"

manifest-tool --username $DOCKER_HUB_USER --password $DOCKER_HUB_PASSWORD push from-args --ignore-missing --platforms $PLATFORMS --template $IMAGE:$VERSION-ARCH --target $IMAGE:$VERSION
manifest-tool --username $DOCKER_HUB_USER --password $DOCKER_HUB_PASSWORD push from-args --ignore-missing --platforms $PLATFORMS --template $IMAGE:$VERSION-alpine-ARCH --target $IMAGE:$VERSION-alpine
manifest-tool --username $DOCKER_HUB_USER --password $DOCKER_HUB_PASSWORD push from-args --ignore-missing --platforms $PLATFORMS --template $IMAGE:alpine-ARCH --target $IMAGE:alpine
manifest-tool --username $DOCKER_HUB_USER --password $DOCKER_HUB_PASSWORD push from-args --ignore-missing --platforms $PLATFORMS --template $IMAGE:latest-ARCH --target $IMAGE:latest
