#!/bin/bash

set -eo pipefail

export PLATFORMS="linux/arm,linux/arm64"

manifes-tool --username $DOCKER_HUB_USER --password $DOCKER_HUB_PASSWORD push from-args --platforms $PLATFORMS --template $IMAGE:$VERSION-ARCH --target $IMAGE:$VERSION
manifes-tool --username $DOCKER_HUB_USER --password $DOCKER_HUB_PASSWORD push from-args --platforms $PLATFORMS --template $IMAGE:$VERSION-alpine-ARCH --target $IMAGE:$VERSION-alpine
manifes-tool --username $DOCKER_HUB_USER --password $DOCKER_HUB_PASSWORD push from-args --platforms $PLATFORMS --template $IMAGE:alpine-ARCH --target $IMAGE:alpine
manifes-tool --username $DOCKER_HUB_USER --password $DOCKER_HUB_PASSWORD push from-args --platforms $PLATFORMS --template $IMAGE:latest-ARCH --target $IMAGE:latest
