#!/bin/bash

set -eo pipefail

_docker(){
    docker ${@}
}

tag() {
    echo -e "\033[1mTagging image: \033[33m${2}\033[0m"
    _docker tag "${1}" "${2}"
}

push() {
    echo -e "\033[1mPushing image: \033[35m${1}\033[0m"
    _docker push "${1}"
}

login() {
    _docker login --username "${1}" --password "${2}" "${3}"
}

logout() {
    _docker logout "${1}"
}

tag "${IMAGE}:${VERSION}" "${IMAGE}:${VERSION}-alpine"
tag "${IMAGE}:${VERSION}" "${IMAGE}:alpine"
tag "${IMAGE}:${VERSION}" "${IMAGE}:latest"
tag "${IMAGE}:${VERSION}-ubuntu" "${IMAGE}:ubuntu"

if [[ -n "${CI_REGISTRY}" ]] && [[ -n "${CI_REGISTRY_IMAGE}" ]]; then
    tag "${IMAGE}:${VERSION}" "${CI_REGISTRY_IMAGE}:${VERSION}"
    tag "${IMAGE}:${VERSION}" "${CI_REGISTRY_IMAGE}:${VERSION}-alpine"
    tag "${IMAGE}:${VERSION}" "${CI_REGISTRY_IMAGE}:alpine"
    tag "${IMAGE}:${VERSION}" "${CI_REGISTRY_IMAGE}:latest"
    tag "${IMAGE}:${VERSION}-ubuntu" "${CI_REGISTRY_IMAGE}:${VERSION}-ubuntu"
    tag "${IMAGE}:${VERSION}-ubuntu" "${CI_REGISTRY_IMAGE}:ubuntu"

    if [[ -n "${CI_REGISTRY_USER}" ]] && [[ -n "${CI_REGISTRY_PASSWORD}" ]]; then
        login "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"

        push "${CI_REGISTRY_IMAGE}:${VERSION}"
        push "${CI_REGISTRY_IMAGE}:${VERSION}-alpine"
        push "${CI_REGISTRY_IMAGE}:alpine"
        push "${CI_REGISTRY_IMAGE}:latest"
        push "${CI_REGISTRY_IMAGE}:${VERSION}-ubuntu"
        push "${CI_REGISTRY_IMAGE}:ubuntu"

        logout "${CI_REGISTRY}"
    fi
fi

if [[ -n "${DOCKER_HUB_USER}" ]] && [[ -n "${DOCKER_HUB_PASSWORD}" ]]; then
    login "${DOCKER_HUB_USER}" "${DOCKER_HUB_PASSWORD}"

    push "${IMAGE}:${VERSION}"
    push "${IMAGE}:${VERSION}-alpine"
    push "${IMAGE}:alpine"
    push "${IMAGE}:latest"
    push "${IMAGE}:${VERSION}-ubuntu"
    push "${IMAGE}:ubuntu"

    logout
fi
