#!/bin/bash

set -eo pipefail

apkArch="$(apk --print-arch)"
case "$apkArch" in
    armhf) runnerArch='arm' ;;
    armv7) runnerArch='arm' ;;
    aarch64) runnerArch='arm64' ;;
    *) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;;
esac

export RUN_AS_PLATFORM=${RUN_AS_PLATFORM:-$runnerArch}

_docker(){
    docker "${@}"
}

tag() {
    echo -e "\033[1mTagging image: \033[33m${2}\033[0m"
    _docker tag "${1}" "${2}"
}

push() {
    echo -e "\033[1mPushing image: \033[35m${1}\033[0m"
    _docker push "${1}"
}

login() {
    echo "${2}" | _docker login --username "${1}" --password-stdin "${3}"
}

logout() {
    _docker logout "${1}"
}

tag "${IMAGE}:${VERSION}-${RUN_AS_PLATFORM}" "${IMAGE}:${VERSION}-alpine-${RUN_AS_PLATFORM}"
tag "${IMAGE}:${VERSION}-${RUN_AS_PLATFORM}" "${IMAGE}:alpine-${RUN_AS_PLATFORM}"
tag "${IMAGE}:${VERSION}-${RUN_AS_PLATFORM}" "${IMAGE}:latest-${RUN_AS_PLATFORM}"
if [[ "${RUN_AS_PLATFORM}" == "arm" ]]; then
    tag "${IMAGE}:${VERSION}-ubuntu" "${IMAGE}:ubuntu"
fi

if [[ -n "${CI_REGISTRY}" ]] && [[ -n "${CI_REGISTRY_IMAGE}" ]]; then
    tag "${IMAGE}:${VERSION}-${RUN_AS_PLATFORM}" "${CI_REGISTRY_IMAGE}:${VERSION}-${RUN_AS_PLATFORM}"
    tag "${IMAGE}:${VERSION}-${RUN_AS_PLATFORM}" "${CI_REGISTRY_IMAGE}:${VERSION}-alpine-${RUN_AS_PLATFORM}"
    tag "${IMAGE}:${VERSION}-${RUN_AS_PLATFORM}" "${CI_REGISTRY_IMAGE}:alpine-${RUN_AS_PLATFORM}"
    tag "${IMAGE}:${VERSION}-${RUN_AS_PLATFORM}" "${CI_REGISTRY_IMAGE}:latest-${RUN_AS_PLATFORM}"
    if [[ "${RUN_AS_PLATFORM}" == "arm" ]]; then
        tag "${IMAGE}:${VERSION}-ubuntu" "${CI_REGISTRY_IMAGE}:${VERSION}-ubuntu"
        tag "${IMAGE}:${VERSION}-ubuntu" "${CI_REGISTRY_IMAGE}:ubuntu"
    fi

    if [[ -n "${CI_REGISTRY_USER}" ]] && [[ -n "${CI_REGISTRY_PASSWORD}" ]]; then
        login "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"

        push "${CI_REGISTRY_IMAGE}:${VERSION}-${RUN_AS_PLATFORM}"
        push "${CI_REGISTRY_IMAGE}:${VERSION}-alpine-${RUN_AS_PLATFORM}"
        push "${CI_REGISTRY_IMAGE}:alpine-${RUN_AS_PLATFORM}"
        push "${CI_REGISTRY_IMAGE}:latest-${RUN_AS_PLATFORM}"
        if [[ "${RUN_AS_PLATFORM}" == "arm" ]]; then
            push "${CI_REGISTRY_IMAGE}:${VERSION}-ubuntu"
            push "${CI_REGISTRY_IMAGE}:ubuntu"
        fi

        logout "${CI_REGISTRY}"
    fi
fi

if [[ -n "${DOCKER_HUB_USER}" ]] && [[ -n "${DOCKER_HUB_PASSWORD}" ]]; then
    login "${DOCKER_HUB_USER}" "${DOCKER_HUB_PASSWORD}"

    push "${IMAGE}:${VERSION}-${RUN_AS_PLATFORM}"
    push "${IMAGE}:${VERSION}-alpine-${RUN_AS_PLATFORM}"
    push "${IMAGE}:alpine-${RUN_AS_PLATFORM}"
    push "${IMAGE}:latest-${RUN_AS_PLATFORM}"
    if [[ "${RUN_AS_PLATFORM}" == "arm" ]]; then
        push "${IMAGE}:${VERSION}-ubuntu"
        push "${IMAGE}:ubuntu"
    fi

    logout
fi
